Repository mesg-foundation/mesg-js, pull requests merged in 2019-09, with the labels that each got.

#126 Update core api to latest version
  package-lock.json
  package.json
  src/protobuf/api/core.proto
  src/protobuf/api/event.proto
  src/protobuf/api/execution.proto
  src/protobuf/api/instance.proto
  src/protobuf/api/process.proto
  src/protobuf/api/service.proto
  src/protobuf/types/event.proto
  src/protobuf/types/execution.proto
  src/protobuf/types/instance.proto
  src/protobuf/types/process.proto
  src/protobuf/types/service.proto
Labels: dependencies

#130 Use MESG struct instead of proto
  copy-proto
  package.json
  src/api/typedef/event.d.ts
  src/api/typedef/execution.d.ts
  src/api/typedef/instance.d.ts
  src/api/typedef/process.d.ts
  src/api/typedef/service.d.ts
  src/application/application.ts
  src/protobuf/api/core.proto
  src/protobuf/api/event.proto
  src/protobuf/api/execution.proto
  src/protobuf/api/instance.proto
  src/protobuf/api/service.proto
  src/protobuf/types/event.proto
  src/protobuf/types/execution.proto
  src/protobuf/types/struct.proto
  src/util/encoder.ts
  tsconfig-istanbul.json
  tsconfig.json
Labels: enhancement

#132 Add support for constants for map
  src/api/typedef/process.d.ts
  src/protobuf/types/process.proto
  src/protobuf/types/struct.proto
  src/util/encoder.ts
Labels: enhancement

#135 New api namespace
  package-lock.json
  package.json
  src/api/typedef/event.d.ts
  src/api/typedef/execution.d.ts
  src/api/typedef/instance.d.ts
  src/api/typedef/process.d.ts
  src/api/typedef/service.d.ts
  src/api/types.ts
  src/protobuf/api/core.proto
  src/protobuf/api/event.proto
  src/protobuf/api/execution.proto
  src/protobuf/api/instance.proto
  src/protobuf/api/process.proto
  src/protobuf/api/service.proto
  src/protobuf/types/event.proto
  src/protobuf/types/execution.proto
  src/protobuf/types/instance.proto
  src/protobuf/types/process.proto
  src/protobuf/types/service.proto
  src/util/grpc.ts
Labels: required update

#136 Update instance api
  src/api/typedef/instance.d.ts
  src/api/types.ts
  src/protobuf/api/instance.proto
  src/util/resolve_test.ts
Labels: required update

#133 Add account api
  copy-proto
  src/api/index.ts
  src/api/mock.ts
  src/api/typedef/account.d.ts
  src/api/types.ts
  src/protobuf/api/account.proto
  src/protobuf/types/account.proto
Labels: enhancement

#141 Remove core api
  copy-proto
  src/api/index.ts
  src/api/mock.ts
  src/api/types.ts
  src/protobuf/api/core.proto
Labels: breaking change
